name: Publish NPM Package

on:
  release:
    types: [ published ]

env:
  NODE_VERSION: ">=18.12.1"

permissions:
  id-token: write
  contents: read

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.FLOWCORE_MACHINE_GITHUB_TOKEN }}
          submodules: true
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.1
        with:
          node-version: "${{ env.NODE_VERSION }}"
          registry-url: "https://registry.npmjs.org"
          cache: yarn
      - name: Yarn install
        run: |
          yarn install --frozen-lockfile
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test --passWithNoTests
      - name: Build
        run: yarn build
      - name: Publish
        run: yarn publish --access public --non-interactive --new-version ${{ steps.version.outputs.value }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
